server:
  port: 8800
mybatis-plus:
  mapper-locations: classpath:com/kxj/auth/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 查看日志
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guigu-oa?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
    username: root
    password: 2787901285q

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8